name: Git Clustering package tests

on:
  push:
    branches: 
      - main 
      - cicd-workflow
  pull_request:
    branches: 
      - main 
      - cicd-workflow

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests with pytest
      run: |
        pytest tests/test_git_clustering.py